import { writable } from "svelte/store";

export const AppStore = writable({
    lang: 'en',
    currentPath: '',
    showLoader: true,
    showModal: false,
    mobileMenuShowed: false,
    aboutWasSlided: 0,
    faqWasSlided: 0,
    walletStatus: 0,
    walletAddress: '',
    someError: false,
    err: '',
    contract: '',
    roadmap: false,
    about: false,
    chain: 'mainnet'
});

export const MintStore = writable({
    loading: false,
    mintContract: null,
    mintInstance: null,
    mintContractAlchemy: null,
    mintInstanceAlchemy: null,
    dustContract: null,
    dustInstance: null,
    nctContract: null,
    nctInstance: null,
    whaleContract: null,
    whaleInstance: null,
    artblockContract: null,
    artblockInstance: null,
    nftboxesContract: null,
    nftboxesInstance: null,
    mintStarted: false,
    mintSucceed: false,
    mintedCount: false,
    maxAmount: 5,
    price: 0,
    allowance: 0,
    amount: 1,
    recieveAmount: 0,
    isWhitelistSale: false,
    nftSelected: [],
    ethAvailable: 0,
    dustAvailable: 0,
    nctAvailable: 0,
    whaleAvailable: 0,
    artblockAvailable: 0,
    boxAvailable: 0,
    whiteListSeconds: 0,
    limitExceed: false,
    currency: "eth",
    currencyType: "eth",
    artblockBalance: 0,
    boxBalance: 0
});